### ISSUE TITLE
Out of memory exception when letting it run for too long

### ISSUE THREAD

**Issue by RayzeEU** [RayzeEU/willhaben-scrapper#14]
When letting the program run for too long it might get an out of memory exception due to some stored resource (I assume from closing and reopening the browser everytime.
Might be good to switch to refreshing instead of closing and re-opening for a default cycle. Closing can be done when an exception occured.

**Comment by Parama91** [comment]
Might be a problem with writing the last_card.txt, because it is opened 2 times but closed only once
